create table if not exists reservations (
  id text primary key,
  reservationid text,
  date text not null,
  name text,
  email text,
  phone text,
  notes text,
  status text not null default 'pending',
  dogcount integer default 0,
  dogs jsonb default '[]'::jsonb,
  dropoff text,
  pickup text,
  created_at timestamptz default now()
);

create table if not exists unavailable_dates (
  date text primary key
);

create index if not exists reservations_date_idx on reservations(date);
create index if not exists reservations_email_idx on reservations(email);
alter table reservations add column if not exists phone text;
alter table reservations add column if not exists notes text;
alter table reservations add column if not exists status text not null default 'pending';

create table if not exists app_settings (
  id integer primary key default 1 check (id = 1),
  max_dogs_per_day integer not null default 5 check (max_dogs_per_day between 1 and 100),
  updated_at timestamptz default now()
);

insert into app_settings (id, max_dogs_per_day) values (1, 5) on conflict (id) do nothing;

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  reservation_id text,
  details jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

alter table reservations enable row level security;
alter table unavailable_dates enable row level security;
alter table app_settings enable row level security;
alter table audit_log enable row level security;

drop policy if exists "Public can read reservations" on reservations;
drop policy if exists "Public can insert reservations" on reservations;
drop policy if exists "Public can delete reservations" on reservations;
drop policy if exists "Public can read unavailable dates" on unavailable_dates;
drop policy if exists "Public can insert unavailable dates" on unavailable_dates;
drop policy if exists "Public can delete unavailable dates" on unavailable_dates;
drop policy if exists "Public can insert reservations" on reservations;
drop policy if exists "Public can delete reservations" on reservations;
drop policy if exists "Public can insert unavailable dates" on unavailable_dates;
drop policy if exists "Public can delete unavailable dates" on unavailable_dates;
drop policy if exists "Authenticated can update reservations" on reservations;
drop policy if exists "Authenticated can delete reservations" on reservations;
drop policy if exists "Authenticated can manage unavailable dates" on unavailable_dates;
drop policy if exists "Public can read settings" on app_settings;
drop policy if exists "Authenticated can manage settings" on app_settings;
drop policy if exists "Authenticated can read audit log" on audit_log;
drop policy if exists "Authenticated can insert audit log" on audit_log;

create policy "Public can read reservations" on reservations for select to anon, authenticated using (true);
create policy "Public can insert reservations" on reservations for insert to anon, authenticated with check (true);
create policy "Public can delete reservations" on reservations for delete to anon, authenticated using (true);
create policy "Public can read unavailable dates" on unavailable_dates for select to anon, authenticated using (true);
create policy "Authenticated can update reservations" on reservations for update to authenticated using (true) with check (true);
create policy "Authenticated can delete reservations" on reservations for delete to authenticated using (true);
create policy "Authenticated can manage unavailable dates" on unavailable_dates for all to authenticated using (true) with check (true);
create policy "Public can read settings" on app_settings for select to anon, authenticated using (true);
create policy "Authenticated can manage settings" on app_settings for all to authenticated using (true) with check (true);
create policy "Authenticated can read audit log" on audit_log for select to authenticated using (true);
create policy "Authenticated can insert audit log" on audit_log for insert to authenticated with check (true);
